apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
        -  name: mysql-container
           image: mysql:latest
           env:
             - name: MYSQL_ROOT_PASSWORD
               value: database
             - name: MYSQL_DATABASE
               value: user
           ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name:  db-service
spec:
  selector:
    name: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
