version : '3.8'
services:
  database:
    image: mysql
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE : login
      MYSQL_ROOT_PASSWORD : database
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - connect
  adminer:
    image: adminer
    container_name: adminer-container
    restart: always
    ports:
      - "9000:8080"
    depends_on:
      - database
    networks:
      - connect
  connect-hub:
    container_name: connect-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://database:3306/login
    depends_on:
      - database
    networks:
      - connect
    restart: on-failure
volumes:
  mysql:
    driver: local
networks:
  connect:
