version : '3.8'
services:
  mysqldb:
    image: mysql
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE : user
      MYSQL_ROOT_PASSWORD : database
    volumes:
      - mysqldb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - connect
  mongodb:
    image: mongo
    container_name: mongodb-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: database
      MONGO_INITDB_DATABASE: event
    ports:
      - "27017:27017"
    networks:
      - connect
    volumes:
      - mongodb:/data/db
  adminer:
    image: dockette/adminer:full
    container_name: adminer-container
    restart: always
    ports:
      - "9000:80"
    depends_on:
      - mysqldb
      - mongodb
    networks:
      - connect
networks:
  connect:
volumes:
  mysqldb:
    driver: local
  mongodb:
    driver: local
